package policy

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/open-policy-agent/opa/v1/rego"
)

type Input struct {
	AppName     string `json:"app_name"`
	Image       string `json:"image"`
	Namespace   string `json:"namespace"`
	Replicas    int    `json:"replicas"`
	CPULimit    string `json:"cpu_limit"`
	MemoryLimit string `json:"memory_limit"`
	Privileged  bool   `json:"privileged"`
}

type Decision struct {
	Allowed bool     `json:"allow"`
	Reasons []string `json:"deny"`
}

type Evaluator interface {
	Evaluate(ctx context.Context, input Input) (Decision, error)
}

type Engine struct {
	query rego.PreparedEvalQuery
}

// NewEngine loads Rego policies from disk once at startup and prepares them for request-time evaluation.
func NewEngine(ctx context.Context, policyPath string) (*Engine, error) {
	query, err := rego.New(
		rego.Query("data.deployment.decision"),
		rego.Load([]string{policyPath}, nil),
	).PrepareForEval(ctx)
	if err != nil {
		return nil, fmt.Errorf("prepare policy query: %w", err)
	}

	return &Engine{query: query}, nil
}

// Evaluate returns the allow/deny decision generated by the loaded policy files.
func (e *Engine) Evaluate(ctx context.Context, input Input) (Decision, error) {
	results, err := e.query.Eval(ctx, rego.EvalInput(input))
	if err != nil {
		return Decision{}, fmt.Errorf("evaluate policy query: %w", err)
	}
	if len(results) == 0 || len(results[0].Expressions) == 0 {
		return Decision{}, errors.New("policy query returned no decision")
	}

	rawDecision, err := json.Marshal(results[0].Expressions[0].Value)
	if err != nil {
		return Decision{}, fmt.Errorf("marshal policy decision: %w", err)
	}

	var decision Decision
	if err := json.Unmarshal(rawDecision, &decision); err != nil {
		return Decision{}, fmt.Errorf("decode policy decision: %w", err)
	}

	return decision, nil
}
