package policy

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/open-policy-agent/opa/v1/rego"
)

type Input struct {
	AppName     string `json:"app_name"`
	Image       string `json:"image"`
	Namespace   string `json:"namespace"`
	Replicas    int    `json:"replicas"`
	CPULimit    string `json:"cpu_limit"`
	MemoryLimit string `json:"memory_limit"`
	Privileged  bool   `json:"privileged"`
}

type Violation struct {
	ControlNo string `json:"control_no"`
	Severity  string `json:"severity"`
	Message   string `json:"message"`
}

type rawViolation struct {
	ControlNo string `json:"control_no"`
}

type rawDecision struct {
	Allowed    bool           `json:"allow"`
	Violations []rawViolation `json:"violations"`
}

type controlMetadata struct {
	Message  string `json:"message"`
	Severity string `json:"severity"`
}

type Decision struct {
	Allowed    bool        `json:"allow"`
	Violations []Violation `json:"violations"`
}

type Evaluator interface {
	Evaluate(ctx context.Context, input Input) (Decision, error)
}

type Engine struct {
	query    rego.PreparedEvalQuery
	controls map[string]controlMetadata
}

// NewEngine loads Rego policies from disk once at startup and prepares them for request-time evaluation.
func NewEngine(ctx context.Context, policyPath string) (*Engine, error) {
	query, err := rego.New(
		rego.Query("data.deployment.decision"),
		rego.Load([]string{policyPath}, nil),
	).PrepareForEval(ctx)
	if err != nil {
		return nil, fmt.Errorf("prepare policy query: %w", err)
	}

	controls, err := loadControls(filepath.Join(policyPath, "controls.json"))
	if err != nil {
		return nil, err
	}

	return &Engine{
		query:    query,
		controls: controls,
	}, nil
}

// Evaluate returns the allow/deny decision generated by the loaded policy files.
func (e *Engine) Evaluate(ctx context.Context, input Input) (Decision, error) {
	results, err := e.query.Eval(ctx, rego.EvalInput(input))
	if err != nil {
		return Decision{}, fmt.Errorf("evaluate policy query: %w", err)
	}
	if len(results) == 0 || len(results[0].Expressions) == 0 {
		return Decision{}, errors.New("policy query returned no decision")
	}

	rawPayload, err := json.Marshal(results[0].Expressions[0].Value)
	if err != nil {
		return Decision{}, fmt.Errorf("marshal policy decision: %w", err)
	}

	var raw rawDecision
	if err := json.Unmarshal(rawPayload, &raw); err != nil {
		return Decision{}, fmt.Errorf("decode policy decision: %w", err)
	}

	violations := make([]Violation, 0, len(raw.Violations))
	for _, item := range raw.Violations {
		control, ok := e.controls[item.ControlNo]
		if !ok {
			return Decision{}, fmt.Errorf("unknown control metadata for %q", item.ControlNo)
		}

		violations = append(violations, Violation{
			ControlNo: item.ControlNo,
			Severity:  control.Severity,
			Message:   control.Message,
		})
	}

	return Decision{
		Allowed:    raw.Allowed,
		Violations: violations,
	}, nil
}

func loadControls(path string) (map[string]controlMetadata, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read controls metadata: %w", err)
	}

	controls := make(map[string]controlMetadata)
	if err := json.Unmarshal(content, &controls); err != nil {
		return nil, fmt.Errorf("decode controls metadata: %w", err)
	}

	return controls, nil
}
